import { adminAuth } from "../config/firebase.js";

export const verifyToken = async (req, res, next) => {
  try {
    const authHeader = req.headers.authorization;

    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      console.log("No token provided in header");
      return res.status(401).json({
        error: "No token provided",
      });
    }

    const token = authHeader.split(" ")[1];

    try {
      const decodedToken = await adminAuth.verifyIdToken(token);
      req.user = decodedToken;
      next();
    } catch (verifyIdError) {
      // If verifyIdToken fails, it might be a custom token (though usually custom tokens are for client-side signInWithCustomToken)
      // For this specific setup, we'll try to use it as-is if it was generated by createCustomToken for testing
      console.error("Token verification failed:", verifyIdError.message);
      
      // NOTE: In a production app, custom tokens should be exchanged for ID tokens on the client
      // This is a temporary bypass for the fallback custom token used in authRoutes.js
      return res.status(401).json({
        error: "Unauthorized: Invalid ID Token. If using custom token, exchange it for ID token first.",
      });
    }
  } catch (error) {
    console.error("AUTH ERROR:", error.message);
    return res.status(401).json({
      error: "Unauthorized",
    });
  }
};